/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'
import { Route as AuthenticatedChatLessonsRouteImport } from './routes/_authenticated/chat.lessons'
import { Route as AuthenticatedChatPlannerRouteImport } from './routes/_authenticated/chat.planner'
import { Route as AuthenticatedChatProgressRouteImport } from './routes/_authenticated/chat.progress'
import { Route as AuthenticatedChatRealityCheckRouteImport } from './routes/_authenticated/chat.reality-check'
import { Route as AuthenticatedChatCourseSubjectIdRouteImport } from './routes/_authenticated/chat.course.$subjectId'
import { Route as AuthenticatedChatLessonSubjectIdLessonIdRouteImport } from './routes/_authenticated/chat.lesson.$subjectId.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const AuthenticatedChatLessonsRoute =
  AuthenticatedChatLessonsRouteImport.update({
    id: '/lessons',
    path: '/lessons',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const AuthenticatedChatPlannerRoute =
  AuthenticatedChatPlannerRouteImport.update({
    id: '/planner',
    path: '/planner',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const AuthenticatedChatProgressRoute =
  AuthenticatedChatProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const AuthenticatedChatRealityCheckRoute =
  AuthenticatedChatRealityCheckRouteImport.update({
    id: '/reality-check',
    path: '/reality-check',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const AuthenticatedChatCourseSubjectIdRoute =
  AuthenticatedChatCourseSubjectIdRouteImport.update({
    id: '/course/$subjectId',
    path: '/course/$subjectId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const AuthenticatedChatLessonSubjectIdLessonIdRoute =
  AuthenticatedChatLessonSubjectIdLessonIdRouteImport.update({
    id: '/lesson/$subjectId/$lessonId',
    path: '/lesson/$subjectId/$lessonId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/share/$token': typeof ShareTokenRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/chat/lessons': typeof AuthenticatedChatLessonsRoute
  '/chat/planner': typeof AuthenticatedChatPlannerRoute
  '/chat/progress': typeof AuthenticatedChatProgressRoute
  '/chat/reality-check': typeof AuthenticatedChatRealityCheckRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/chat/course/$subjectId': typeof AuthenticatedChatCourseSubjectIdRoute
  '/chat/lesson/$subjectId/$lessonId': typeof AuthenticatedChatLessonSubjectIdLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/api/chat': typeof ApiChatRoute
  '/share/$token': typeof ShareTokenRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/chat/lessons': typeof AuthenticatedChatLessonsRoute
  '/chat/planner': typeof AuthenticatedChatPlannerRoute
  '/chat/progress': typeof AuthenticatedChatProgressRoute
  '/chat/reality-check': typeof AuthenticatedChatRealityCheckRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/chat/course/$subjectId': typeof AuthenticatedChatCourseSubjectIdRoute
  '/chat/lesson/$subjectId/$lessonId': typeof AuthenticatedChatLessonSubjectIdLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/share/$token': typeof ShareTokenRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/chat/lessons': typeof AuthenticatedChatLessonsRoute
  '/_authenticated/chat/planner': typeof AuthenticatedChatPlannerRoute
  '/_authenticated/chat/progress': typeof AuthenticatedChatProgressRoute
  '/_authenticated/chat/reality-check': typeof AuthenticatedChatRealityCheckRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/chat/course/$subjectId': typeof AuthenticatedChatCourseSubjectIdRoute
  '/_authenticated/chat/lesson/$subjectId/$lessonId': typeof AuthenticatedChatLessonSubjectIdLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/chat'
    | '/api/chat'
    | '/share/$token'
    | '/chat/$threadId'
    | '/chat/lessons'
    | '/chat/planner'
    | '/chat/progress'
    | '/chat/reality-check'
    | '/chat/'
    | '/chat/course/$subjectId'
    | '/chat/lesson/$subjectId/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/api/chat'
    | '/share/$token'
    | '/chat/$threadId'
    | '/chat/lessons'
    | '/chat/planner'
    | '/chat/progress'
    | '/chat/reality-check'
    | '/chat'
    | '/chat/course/$subjectId'
    | '/chat/lesson/$subjectId/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/_authenticated/chat'
    | '/api/chat'
    | '/share/$token'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/chat/lessons'
    | '/_authenticated/chat/planner'
    | '/_authenticated/chat/progress'
    | '/_authenticated/chat/reality-check'
    | '/_authenticated/chat/'
    | '/_authenticated/chat/course/$subjectId'
    | '/_authenticated/chat/lesson/$subjectId/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  ApiChatRoute: typeof ApiChatRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/chat/lessons': {
      id: '/_authenticated/chat/lessons'
      path: '/lessons'
      fullPath: '/chat/lessons'
      preLoaderRoute: typeof AuthenticatedChatLessonsRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/chat/planner': {
      id: '/_authenticated/chat/planner'
      path: '/planner'
      fullPath: '/chat/planner'
      preLoaderRoute: typeof AuthenticatedChatPlannerRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/chat/progress': {
      id: '/_authenticated/chat/progress'
      path: '/progress'
      fullPath: '/chat/progress'
      preLoaderRoute: typeof AuthenticatedChatProgressRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/chat/reality-check': {
      id: '/_authenticated/chat/reality-check'
      path: '/reality-check'
      fullPath: '/chat/reality-check'
      preLoaderRoute: typeof AuthenticatedChatRealityCheckRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/chat/course/$subjectId': {
      id: '/_authenticated/chat/course/$subjectId'
      path: '/course/$subjectId'
      fullPath: '/chat/course/$subjectId'
      preLoaderRoute: typeof AuthenticatedChatCourseSubjectIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/chat/lesson/$subjectId/$lessonId': {
      id: '/_authenticated/chat/lesson/$subjectId/$lessonId'
      path: '/lesson/$subjectId/$lessonId'
      fullPath: '/chat/lesson/$subjectId/$lessonId'
      preLoaderRoute: typeof AuthenticatedChatLessonSubjectIdLessonIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedChatLessonsRoute: typeof AuthenticatedChatLessonsRoute
  AuthenticatedChatPlannerRoute: typeof AuthenticatedChatPlannerRoute
  AuthenticatedChatProgressRoute: typeof AuthenticatedChatProgressRoute
  AuthenticatedChatRealityCheckRoute: typeof AuthenticatedChatRealityCheckRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
  AuthenticatedChatCourseSubjectIdRoute: typeof AuthenticatedChatCourseSubjectIdRoute
  AuthenticatedChatLessonSubjectIdLessonIdRoute: typeof AuthenticatedChatLessonSubjectIdLessonIdRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedChatLessonsRoute: AuthenticatedChatLessonsRoute,
  AuthenticatedChatPlannerRoute: AuthenticatedChatPlannerRoute,
  AuthenticatedChatProgressRoute: AuthenticatedChatProgressRoute,
  AuthenticatedChatRealityCheckRoute: AuthenticatedChatRealityCheckRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  AuthenticatedChatCourseSubjectIdRoute: AuthenticatedChatCourseSubjectIdRoute,
  AuthenticatedChatLessonSubjectIdLessonIdRoute:
    AuthenticatedChatLessonSubjectIdLessonIdRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  ApiChatRoute: ApiChatRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
